pipeline {
    //agent any
    agent {
        docker {
            image 'ubuntu:20.04'
            label 'main'
            args '--network host --rm --name test-pipeline-con'
            alwaysPull true
            //registryCredentialsId 'ms_dockerhub_credential'
        }
    }
    triggers {
        issueCommentTrigger('.*start build.*')
        githubPush()
    }
    stages {
        stage('Get methods') {
            steps {
                sh 'ls'
                sh 'pwd'
                sh 'apt update -y'
                sh 'apt install -y lsb_release'
                sh 'lsb_release -a'
                sh 'hostname'
            }
        }
    }
}

